#!/bin/sh

cli=/Applications/Karabiner.app/Contents/Library/bin/karabiner

$cli set remap.commandR2escape 1
/bin/echo -n .
$cli set remap.controlL2optionL 1
/bin/echo -n .
$cli set remap.option_r_to_right_click 1
/bin/echo -n .
$cli set remap.shiftR2enter 1
/bin/echo -n .
$cli set repeat.initial_wait 250
/bin/echo -n .
$cli set repeat.wait 33
/bin/echo -n .
/bin/echo
