#!/usr/bin/env bash


#*******************************************************
#                       aliases
#*******************************************************
alias sp="/Users/tsanthosh/gtel/src-sw00176-gtel-aggregators/script/local/start-postgres.sh"
alias cdd="/Users/tsanthosh/gtel/src-sw00176-gtel-aggregators/script/local/create-databases.sh"
#new_alias_adding_marker
alias tv="adb connect 192.168.43.244"
alias ll="ls -alF"
alias la="ls -A"
alias l="ls -CF"

alias down='cd ~/Downloads'
alias des='cd ~/Desktop'
alias fuck='eval $(thefuck $(fc -ln -1))'
alias ff="fuck"
alias rmr="rm -rf"

alias grep='grep --color'


alias mute="osascript -e 'set volume output muted true'"
alias unmute="osascript -e 'set volume output muted false'"


alias grep='grep --color=auto'

alias jrun="java -jar build/libs/*.jar"
alias gu="cd ~/Documents/mc-strategic/"
alias api="cd ~/Documents/pricing/pricing-api/"
alias sc="cd ~/Documents/pricing/service-contract-api"
alias auth="cd ~/Documents/pricing/authorization_service"

alias sb="source ~/.bash_profile"


alias cd..='cd ../'                         # Go back 1 directory level (for fast typers)
alias ..='cd ../'                           # Go back 1 directory level
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias f='open -a Finder ./'                 # f:            Opens current directory in MacOS Finder
alias c='clear'                             # c:            Clear terminal display
alias lr='ls -R | grep ":$" | sed -e '\''s/:$//'\'' -e '\''s/[^-][^\/]*\//--/g'\'' -e '\''s/^/   /'\'' -e '\''s/-/|/'\'' | less'
alias qfind="find . -name "                 # qfind:    Quickly search for file

# git aliases
alias gs="git status"
alias gsh="git stash"
alias gp="git push origin HEAD"
alias gpn="git push origin HEAD --no-verify"
alias gsp="git submodule update --init --recursive"
alias gb="git branch"
alias gc="git checkout"
alias gcm="git checkout master"
alias gt="git checkout team/miracle"
alias gcp="git cherry-pick"
alias gcb="git checkout -b"
alias gv="git commit -v"
alias gva="git commit -va"
alias gvn="git commit -va --no-verify"
alias gd="git diff"
alias gsw="git show"
alias g="git"
alias amendlast="git commit --amend --no-edit"
alias pserver="python3 -m http.server"


alias e="echo"
alias v="vim"
alias r="ranger"
alias lo="locate"


#docker_aliases

alias dl="docker ps -l -q"
alias dps="docker ps"
alias dpa="docker ps -a"
alias di="docker images"

# Get container IP
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"

# Run deamonized container, e.g., $dkd base /bin/echo hello
alias dkd="docker run -d -P"

# Run interactive container, e.g., $dki base /bin/bash
alias dki="docker run -i -t -P"

# Execute interactive container, e.g., $dex base /bin/bash
alias dex="docker exec -i -t"

########## Node ##############

alias bb='npm run build'
alias ss='npm run start'

##### JSON ###########

#format json in clipboard and copy
alias fj="pbpaste | jq '.' | pbcopy"


##### ANDROID #######
alias adbtcp="adb reverse tcp:8081 tcp:8081"


alias bi='brew install'


alias pp='pbpaste'
alias cc='pbcopy'
alias pc="pbpaste  |  sed 's/^\$ //' | tr '\n' ' '  | pbcopy; echo 'Removed $ and new line character!'"

alias ip='ipconfig getifaddr en0'

alias u="youtube-dl --download-archive ~/Desktop/archive.txt -i "

alias py="python3"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias trust="sudo xattr -d com.apple.quarantine"
alias gw="./gradlew"


alias got="generate_otp_with_secret_from_clipboard"

alias is="itermocil "

alias npum="/Users/tsanthosh/.nvm/versions/node/v18.18.2/bin/npm"
alias esl="./node_modules/eslint/bin/eslint.js"

alias code="open -a \"/Applications/Visual Studio Code.app\""
alias idea="/Applications/IntelliJ\ IDEA.app/Contents/MacOS/idea"
alias tn="tabname"

alias cbm="mv ~/.gradle/init.d.bk ~/.gradle/init.d"
alias pem="mv ~/.gradle/init.d ~/.gradle/init.d.bk"
alias nt="nvm use 20"
alias gwork='gituser_work'
alias gper='gituser_personal'

alias oa="code ~/piano_mode/mac/bash/aliases"
alias piano="code ~/piano_mode"
alias antt="./ant/bin/ant"
alias emptycommit="git commit --allow-empty -m 'Trigger Build'"
alias conf="code ~/work/chargebee-app/webapp/conf/environment/assets.conf"

# alias auto-click="/Users/tsanthosh/work/auto-web-login/auto-click/target/release/auto-click"
alias co="code ."
alias tf="terraform"

alias fn="find . -type f -iname"
alias myip='curl ipinfo.io/ip'
alias weather='curl wttr.in/chennai'

alias :q='exit'
alias psf="ps -ef | grep"


alias hi='cd'
alias jv="java -version"
alias gmp="./gradlew publishToMavenLocal"
alias assemble="./gradlew assemble"
alias ts="convert_timestamp"
alias ag="alias | grep "