#!/usr/bin/env bash

# Colors
BIGreen="\[\033[1;92m\]"
BIPurple="\[\033[1;95m\]"
BCyan="\[\033[1;36m\]"
BIWhite="\[\033[1;97m\]"
IYellow="\[\033[0;93m\]"

Green="\033[1;92m"
RedResult="\[\033[0;31m\]"
GreenResult="\[\033[0;32m\]"

# Short dir toggle
alias sdn='export short_dir_name=true'
alias ldn='export short_dir_name=false'

# Efficient Git status check
function parse_git_dirty {
  [[ -n $(git status --porcelain 2>/dev/null) ]] && echo "*"
}

function parse_git_branch {
  local branch_info
  branch_info=$(git branch --no-color 2>/dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1/")
  
  if [ -n "$branch_info" ]; then
    echo "[$branch_info$(parse_git_dirty)]"
  fi
}

function get_date {
  LC_TIME=en_US.UTF-8 date +"%I:%M:%S %p"
}

function get_directory_name {
  if [ "$short_dir_name" = true ]; then
    echo -n "./$(basename "$PWD")"
  else
    echo -n "${PWD/#$HOME/~}"
  fi
}

function get_previous_command_result {
  local exit_code=$?
  echo -n "$exit_code"
}

export BASH_SILENCE_DEPRECATION_WARNING=1

# Final prompt string
export PS1='

($(get_previous_command_result)) '"$BIGreen"'$(get_date)'"$BIPurple"' $(get_directory_name) '"$BCyan"'$(parse_git_branch)'"$BIWhite"'
\$'"$IYellow "' '