#!/bin/bash

MY_PIANO_MODE_HOME="$1"
MAC_HOME="$MY_PIANO_MODE_HOME/mac"
MAC_BASH_HOME="$MAC_HOME/bash"
MAC_BASHRC="$MAC_BASH_HOME/rc"

MAC_SEIL_DEFAULT="$MAC_HOME/seil/default"
MAC_SEIL_MODIFIED="$MAC_HOME/seil/modified"

set completion-ignore-case on

HISTCONTROL=ignoredups:ignorespace
HISTSIZE=100000
HISTFILESIZE=2000000

shopt -s histappend
shopt -s checkwinsize
shopt -s cdspell




